@echo off
echo.
echo Dropping database and login...

echo Dropping EmployeeTraining Database...
sqlcmd -i "Release_1.0_DB_Scripts\DropDatabase.sql" -b -o %DB_LOGS%\R1_001_DropDatabaseOutput.txt
echo Dropping EmployeeTraining Login...
sqlcmd -i "Release_1.0_DB_Scripts\DropLogin.sql" -b -o %DB_LOGS%\R1_002_DropLoginOutput.txt